/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'isProductive' : boolean,
  'startTime' : Time,
  'duration' : bigint,
  'endTime' : Time,
  'userId' : Principal,
  'date' : Time,
  'habitId' : bigint,
  'earnings' : bigint,
  'notes' : string,
  'customName' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Coupon {
  'id' : bigint,
  'expiresAt' : [] | [Time],
  'code' : string,
  'createdAt' : Time,
  'usedCount' : bigint,
  'discountPercent' : bigint,
  'usageLimit' : bigint,
}
export interface Habit {
  'id' : bigint,
  'goalType' : HabitGoal,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
  'goalValue' : bigint,
  'isActive' : boolean,
  'streakCount' : bigint,
}
export type HabitGoal = { 'daily' : null } |
  { 'weekly' : null };
export interface HabitStreak {
  'active' : boolean,
  'totalEntries' : bigint,
  'habitId' : bigint,
  'streakCount' : bigint,
}
export interface PaymentRequest {
  'id' : bigint,
  'status' : PaymentStatus,
  'couponCode' : [] | [string],
  'userId' : Principal,
  'plan' : Plan,
  'cycle' : [] | [PlanCycle],
  'submittedAt' : Time,
  'verifiedAt' : [] | [Time],
  'transactionId' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Plan = { 'starter' : null } |
  { 'premium' : null } |
  { 'free' : null };
export type PlanCycle = { 'monthly' : null } |
  { 'yearly' : null };
export interface PlatformStats {
  'totalActivities' : bigint,
  'totalPaymentRequests' : bigint,
  'totalHabits' : bigint,
  'totalUsers' : bigint,
}
export interface StreakDay { 'date' : Time, 'habitId' : bigint }
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'plan' : Plan,
  'email' : string,
  'planExpiry' : [] | [Time],
  'phone' : string,
  'lastLogin' : [] | [Time],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStreaks {
  'totalActivities' : bigint,
  'userId' : Principal,
  'activeStreak' : bigint,
  'habits' : Array<HabitStreak>,
  'longestStreak' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePaymentRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCoupon' : ActorMethod<
    [string, bigint, bigint, [] | [Time]],
    undefined
  >,
  'createHabit' : ActorMethod<[string, HabitGoal, bigint, string], undefined>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteActivity' : ActorMethod<[bigint], undefined>,
  'deleteCoupon' : ActorMethod<[string], undefined>,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'getActivities' : ActorMethod<
    [Principal, [] | [bigint], [] | [boolean]],
    Array<Activity>
  >,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'getHabitStreak' : ActorMethod<[bigint], bigint>,
  'getHabitStreaks' : ActorMethod<[bigint], Array<StreakDay>>,
  'getHabits' : ActorMethod<[Principal, [] | [HabitGoal]], Array<Habit>>,
  'getMyPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getPendingPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStreak' : ActorMethod<[Principal], bigint>,
  'getUserStreaks' : ActorMethod<[Principal], UserStreaks>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listCoupons' : ActorMethod<[], Array<Coupon>>,
  'logActivity' : ActorMethod<
    [bigint, string, Time, Time, bigint, boolean, bigint, string, Time],
    undefined
  >,
  'rejectPaymentRequest' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCoupons' : ActorMethod<[string], Array<Coupon>>,
  'selfPromoteAdmin' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setUserPlan' : ActorMethod<[Principal, Plan, [] | [Time]], undefined>,
  'submitPaymentRequest' : ActorMethod<
    [Plan, [] | [PlanCycle], string, [] | [string]],
    undefined
  >,
  'updateActivity' : ActorMethod<
    [bigint, bigint, string, Time, Time, bigint, boolean, bigint, string, Time],
    undefined
  >,
  'updateHabit' : ActorMethod<
    [bigint, string, HabitGoal, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];