/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const HabitGoal = IDL.Variant({
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'isProductive' : IDL.Bool,
  'startTime' : Time,
  'duration' : IDL.Nat,
  'endTime' : Time,
  'userId' : IDL.Principal,
  'date' : Time,
  'habitId' : IDL.Nat,
  'earnings' : IDL.Nat,
  'notes' : IDL.Text,
  'customName' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Plan = IDL.Variant({
  'starter' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const PlanCycle = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'plan' : Plan,
  'cycle' : IDL.Opt(PlanCycle),
  'submittedAt' : Time,
  'verifiedAt' : IDL.Opt(Time),
  'transactionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'plan' : Plan,
  'email' : IDL.Text,
  'planExpiry' : IDL.Opt(Time),
  'phone' : IDL.Text,
  'lastLogin' : IDL.Opt(Time),
});
export const Coupon = IDL.Record({
  'id' : IDL.Nat,
  'expiresAt' : IDL.Opt(Time),
  'code' : IDL.Text,
  'createdAt' : Time,
  'usedCount' : IDL.Nat,
  'discountPercent' : IDL.Nat,
  'usageLimit' : IDL.Nat,
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'goalType' : HabitGoal,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
  'goalValue' : IDL.Nat,
  'isActive' : IDL.Bool,
  'streakCount' : IDL.Nat,
});
export const PlatformStats = IDL.Record({
  'totalActivities' : IDL.Nat,
  'totalPaymentRequests' : IDL.Nat,
  'totalHabits' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCoupon' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(Time)],
      [],
      [],
    ),
  'createHabit' : IDL.Func([IDL.Text, HabitGoal, IDL.Nat, IDL.Text], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteActivity' : IDL.Func([IDL.Nat], [], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'getActivities' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'getHabits' : IDL.Func(
      [IDL.Principal, IDL.Opt(HabitGoal)],
      [IDL.Vec(Habit)],
      ['query'],
    ),
  'getMyPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getPendingPaymentRequests' : IDL.Func(
      [],
      [IDL.Vec(PaymentRequest)],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'logActivity' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Time,
        Time,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
        IDL.Text,
        Time,
      ],
      [],
      [],
    ),
  'rejectPaymentRequest' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCoupons' : IDL.Func([IDL.Text], [IDL.Vec(Coupon)], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setUserPlan' : IDL.Func([IDL.Principal, Plan, IDL.Opt(Time)], [], []),
  'submitPaymentRequest' : IDL.Func(
      [Plan, IDL.Opt(PlanCycle), IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateActivity' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        Time,
        Time,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
        IDL.Text,
        Time,
      ],
      [],
      [],
    ),
  'updateHabit' : IDL.Func(
      [IDL.Nat, IDL.Text, HabitGoal, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const HabitGoal = IDL.Variant({ 'daily' : IDL.Null, 'weekly' : IDL.Null });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'isProductive' : IDL.Bool,
    'startTime' : Time,
    'duration' : IDL.Nat,
    'endTime' : Time,
    'userId' : IDL.Principal,
    'date' : Time,
    'habitId' : IDL.Nat,
    'earnings' : IDL.Nat,
    'notes' : IDL.Text,
    'customName' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Plan = IDL.Variant({
    'starter' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const PlanCycle = IDL.Variant({ 'monthly' : IDL.Null, 'yearly' : IDL.Null });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'plan' : Plan,
    'cycle' : IDL.Opt(PlanCycle),
    'submittedAt' : Time,
    'verifiedAt' : IDL.Opt(Time),
    'transactionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'plan' : Plan,
    'email' : IDL.Text,
    'planExpiry' : IDL.Opt(Time),
    'phone' : IDL.Text,
    'lastLogin' : IDL.Opt(Time),
  });
  const Coupon = IDL.Record({
    'id' : IDL.Nat,
    'expiresAt' : IDL.Opt(Time),
    'code' : IDL.Text,
    'createdAt' : Time,
    'usedCount' : IDL.Nat,
    'discountPercent' : IDL.Nat,
    'usageLimit' : IDL.Nat,
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'goalType' : HabitGoal,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
    'goalValue' : IDL.Nat,
    'isActive' : IDL.Bool,
    'streakCount' : IDL.Nat,
  });
  const PlatformStats = IDL.Record({
    'totalActivities' : IDL.Nat,
    'totalPaymentRequests' : IDL.Nat,
    'totalHabits' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCoupon' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(Time)],
        [],
        [],
      ),
    'createHabit' : IDL.Func([IDL.Text, HabitGoal, IDL.Nat, IDL.Text], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteActivity' : IDL.Func([IDL.Nat], [], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'getActivities' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'getHabits' : IDL.Func(
        [IDL.Principal, IDL.Opt(HabitGoal)],
        [IDL.Vec(Habit)],
        ['query'],
      ),
    'getMyPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
    'getPendingPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'logActivity' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Time,
          Time,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
          IDL.Text,
          Time,
        ],
        [],
        [],
      ),
    'rejectPaymentRequest' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCoupons' : IDL.Func([IDL.Text], [IDL.Vec(Coupon)], ['query']),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setUserPlan' : IDL.Func([IDL.Principal, Plan, IDL.Opt(Time)], [], []),
    'submitPaymentRequest' : IDL.Func(
        [Plan, IDL.Opt(PlanCycle), IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateActivity' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          Time,
          Time,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
          IDL.Text,
          Time,
        ],
        [],
        [],
      ),
    'updateHabit' : IDL.Func(
        [IDL.Nat, IDL.Text, HabitGoal, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };