/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'isProductive' : boolean,
  'startTime' : Time,
  'duration' : bigint,
  'endTime' : Time,
  'userId' : Principal,
  'date' : Time,
  'habitId' : bigint,
  'earnings' : bigint,
  'notes' : string,
  'customName' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Coupon {
  'id' : bigint,
  'expiresAt' : [] | [Time],
  'code' : string,
  'createdAt' : Time,
  'usedCount' : bigint,
  'discountPercent' : bigint,
  'usageLimit' : bigint,
}
export interface Habit {
  'id' : bigint,
  'goalType' : HabitGoal,
  'userId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
  'goalValue' : bigint,
  'isActive' : boolean,
  'streakCount' : bigint,
}
export type HabitGoal = { 'daily' : null } |
  { 'weekly' : null };
export interface PaymentRequest {
  'id' : bigint,
  'status' : PaymentStatus,
  'couponCode' : [] | [string],
  'userId' : Principal,
  'plan' : Plan,
  'cycle' : [] | [PlanCycle],
  'submittedAt' : Time,
  'verifiedAt' : [] | [Time],
  'transactionId' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Plan = { 'starter' : null } |
  { 'premium' : null } |
  { 'free' : null };
export type PlanCycle = { 'monthly' : null } |
  { 'yearly' : null };
export interface PlatformStats {
  'totalActivities' : bigint,
  'totalPaymentRequests' : bigint,
  'totalHabits' : bigint,
  'totalUsers' : bigint,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'plan' : Plan,
  'email' : string,
  'planExpiry' : [] | [Time],
  'phone' : string,
  'lastLogin' : [] | [Time],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Approve a payment request and update the user's plan. Admin only.
   */
  'approvePaymentRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Assigns a role to a user (requires admin privileges).
   */
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a coupon. Admin only.
   */
  'createCoupon' : ActorMethod<
    [string, bigint, bigint, [] | [Time]],
    undefined
  >,
  /**
   * / Create a new habit for the calling user.
   */
  'createHabit' : ActorMethod<[string, HabitGoal, bigint, string], undefined>,
  /**
   * / Delete the calling user's own account.
   */
  'deleteAccount' : ActorMethod<[], undefined>,
  /**
   * / Delete an activity. Only the owner (or admin) may delete.
   */
  'deleteActivity' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete a coupon by code. Admin only.
   */
  'deleteCoupon' : ActorMethod<[string], undefined>,
  /**
   * / Delete a habit. Only the owner (or admin) may delete.
   */
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  /**
   * / Get activities for a user. Users may only query their own; admins may
   * / query any user's activities.
   */
  'getActivities' : ActorMethod<
    [Principal, [] | [bigint], [] | [boolean]],
    Array<Activity>
  >,
  /**
   * / Get all payment requests. Admin only.
   */
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  /**
   * / Returns all user profiles. Admin only.
   */
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  /**
   * / Get the calling user's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Look up a coupon by code. Only registered users may validate coupons.
   */
  'getCoupon' : ActorMethod<[string], [] | [Coupon]>,
  /**
   * / Get habits for a user. Users may only query their own habits; admins may
   * / query any user's habits.
   */
  'getHabits' : ActorMethod<[Principal, [] | [HabitGoal]], Array<Habit>>,
  /**
   * / Get the calling user's own payment requests.
   */
  'getMyPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  /**
   * / Get all pending payment requests. Admin only.
   */
  'getPendingPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  /**
   * / Platform-wide statistics. Admin only.
   */
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  /**
   * / Fetch another user's profile.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check if the caller is approved (true for admins)
   */
  'isCallerApproved' : ActorMethod<[], boolean>,
  /**
   * / Admin: List all approval entries
   */
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  /**
   * / List all coupons. Admin only.
   */
  'listCoupons' : ActorMethod<[], Array<Coupon>>,
  /**
   * / Log a new activity for the calling user.
   */
  'logActivity' : ActorMethod<
    [bigint, string, Time, Time, bigint, boolean, bigint, string, Time],
    undefined
  >,
  /**
   * / Reject a payment request. Admin only.
   */
  'rejectPaymentRequest' : ActorMethod<[bigint], undefined>,
  /**
   * / Request approval as a new user
   */
  'requestApproval' : ActorMethod<[], undefined>,
  /**
   * / Save / update the calling user's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search coupons by code substring. Admin only.
   */
  'searchCoupons' : ActorMethod<[string], Array<Coupon>>,
  /**
   * / Allows the caller to promote themselves to admin ONLY when no admin
   * / currently exists in the system (i.e. first-time bootstrap).
   * / The caller must already be a registered user (have a profile).
   */
  'selfPromoteAdmin' : ActorMethod<[], undefined>,
  /**
   * / Admin: Set approval status for a user
   */
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  /**
   * / Admin: Set a user's plan.
   */
  'setUserPlan' : ActorMethod<[Principal, Plan, [] | [Time]], undefined>,
  /**
   * / Submit a payment request. Only registered users may submit.
   */
  'submitPaymentRequest' : ActorMethod<
    [Plan, [] | [PlanCycle], string, [] | [string]],
    undefined
  >,
  /**
   * / Update an existing activity. Only the owner (or admin) may update.
   */
  'updateActivity' : ActorMethod<
    [bigint, bigint, string, Time, Time, bigint, boolean, bigint, string, Time],
    undefined
  >,
  /**
   * / Update an existing habit. Only the owner (or admin) may update.
   */
  'updateHabit' : ActorMethod<
    [bigint, string, HabitGoal, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];